### ISSUE TITLE
Duplicate time point issues: make_cmip_annualMeans3D.py

### ISSUE THREAD

**Issue by durack1** [durack1/cmip5#10]
```
** Processing xml: cmip5.EC-EARTH.rcp45.r14i1p1.mo.ocn.Omon.so.ver-v20120307.latestX.WARN2.xml
25yr annual calculation for cmip5.EC-EARTH.rcp45.r14i1p1.mo.ocn.Omon.so.ver-v20120307.latestX.WARN2.xml
** Outfile: cmip5.EC-EARTH.rcp45.r14i1p1.an.so.ver-v20120307.2006-2009.nc being processed **
2006-1-1 0:0:0.0 2009-1-1 0:0:0.0
(0, 1097)
** Processing annual means for 2006 to 2009 **
(1097, 42, 292, 362)
   id: time
   Designated a time axis.
   units:  days since 2006-01-01 00:00:00
   Length: 1097
   First:  0.0
   Last:   1096.0
   Other axis attributes:
      calendar: gregorian
      axis: T
   Python id:  0x7f1f594275d0

['000', '01', 2006-1-1 0:0:0.0]
['1096', '05', 2009-1-1 0:0:0.0]
Traceback (most recent call last):
  File ".//make_cmip_annualMeans3D.py", line 292, in <module>
    dan = cdu.YEAR(d)
  File "/usr/local/uvcdat/2015-04-09/lib/python2.7/site-packages/cdutil/times.py", line 1291, in get
    m = mergeTime(s,statusbar=statusbar,fill_value=getattr(slab,'fill_value',1.e20))
  File "/usr/local/uvcdat/2015-04-09/lib/python2.7/site-packages/cdutil/times.py", line 199, in mergeTime
    raise Exception,err
Exception: Error in merging process : duplicate time point
2006-7-2 12:0:0.0 is duplicated, cannot merge[]
```
And same issue with `** Processing xml: cmip5.EC-EARTH.rcp45.r13i1p1.mo.ocn.Omon.thetao.ver-v20120303.latestX.WARN2.xml`

**Comment by durack1** [comment]
```
** Processing xml: cmip5.EC-EARTH.rcp85.r14i1p1.mo.ocn.Omon.thetao.ver-v1.latestX.WARN2.xml
25yr annual calculation for cmip5.EC-EARTH.rcp85.r14i1p1.mo.ocn.Omon.thetao.ver-v1.latestX.WARN2.xml
** Outfile: cmip5.EC-EARTH.rcp85.r14i1p1.an.thetao.ver-v1.2006-2009.nc being processed **
2006-1-1 0:0:0.0 2009-1-1 0:0:0.0
(0, 1097)
** Processing annual means for 2006 to 2009 **
(1097, 42, 292, 362)
   id: time
   Designated a time axis.
   units:  days since 2006-01-01 00:00:00
   Length: 1097
   First:  0.0
   Last:   1096.0
   Other axis attributes:
      calendar: gregorian
      axis: T
   Python id:  0x7f723d5b3a90

['000', '01', 2006-1-1 0:0:0.0]
['1096', '05', 2009-1-1 0:0:0.0]
Traceback (most recent call last):
  File ".//make_cmip_annualMeans3D.py", line 292, in <module>
    dan = cdu.YEAR(d)
  File "/usr/local/uvcdat/2015-04-09/lib/python2.7/site-packages/cdutil/times.py", line 1291, in get
    m = mergeTime(s,statusbar=statusbar,fill_value=getattr(slab,'fill_value',1.e20))
  File "/usr/local/uvcdat/2015-04-09/lib/python2.7/site-packages/cdutil/times.py", line 199, in mergeTime
    raise Exception,err
Exception: Error in merging process : duplicate time point
2006-7-2 12:0:0.0 is duplicated, cannot merge[]
```
