### ISSUE TITLE
Faulty DRS-related failure: make_cmip5_xmls.py

### ISSUE THREAD

**Issue by durack1** [durack1/cmip5#37]
```
[durack1@oceanonly cmip5]$ make_cmip5_xml.py report
160402_200052                                      
** Report mode - no *.xml files will be written ** 
master pid2932                                     
UV-CDAT: /usr/local/uvcdat/2016-02-17/bin/python   
p1 pid: 2943                                       
p2 pid: 2948                                       
p3 pid: 2954                                       
p4 pid: 2964                                       
p5 pid: 2971                                       
p6 pid: 2977                                       
p7 pid: 2990                                       
p8 pid: 3004                                       
p9 pid: 3011                                       
gdo2_scratch  scan complete.. 0      paths total; 0      output files to be written (118 vars sampled)
gdo2_data     scan complete.. 2222   paths total; 1184   output files to be written (118 vars sampled)
pathToFile - Exception: list index out of range /cmip5_css01/scratch/cmip5/output1/MRI                
[u'', u'cmip5_css01', u'data', u'cmip5', u'CNRM-CERFACS', u'CNRM-CM5', u'amip', u'mon', u'land', u'Lmon', u'r1i1p1', u'v20111018', u'mrsos']
Process Process-6:
Traceback (most recent call last):
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File ".//make_cmip5_xml.py", line 282, in pathToFile
    if 'HadGEM2-AO' in model and experiment in ['historical','rcp26','rcp45','rcp60','rcp85']:
UnboundLocalError: local variable 'model' referenced before assignment
css01_scratch scan complete.. 46267  paths total; 25482  output files to be written (118 vars sampled)
Traceback (most recent call last):
  File ".//make_cmip5_xml.py", line 711, in <module>
    [css01_data_outfiles,css01_data_outfiles_paths,time_since_start,i1,i2,len_vars] = queue5.get_nowait()
  File "<string>", line 2, in get_nowait
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/multiprocessing/managers.py", line 774, in _callmethod
    raise convert_to_error(kind, result)
Queue.Empty
Process Process-4:
Traceback (most recent call last):
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File ".//make_cmip5_xml.py", line 311, in pathToFile
    queue1.put_nowait([data_outfiles,data_outfiles_paths,time_since_start,i1,i2,len_vars]) ; # Queue
  File "<string>", line 2, in put_nowait
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/multiprocessing/managers.py", line 755, in _callmethod
    self._connect()
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/multiprocessing/managers.py", line 742, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/multiprocessing/connection.py", line 169, in Client
    c = SocketClient(address)
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/multiprocessing/connection.py", line 308, in SocketClient
    s.connect(address)
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 2] No such file or directory
pathToFile - Exception: list index out of range /cmip5_css02/scratch/cmip5/output1/CCCma/CanESM2/jfyfe_special
Process Process-5:
Traceback (most recent call last):
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File ".//make_cmip5_xml.py", line 311, in pathToFile
    queue1.put_nowait([data_outfiles,data_outfiles_paths,time_since_start,i1,i2,len_vars]) ; # Queue
  File "<string>", line 2, in put_nowait
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/multiprocessing/managers.py", line 755, in _callmethod
    self._connect()
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/multiprocessing/managers.py", line 742, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/multiprocessing/connection.py", line 169, in Client
    c = SocketClient(address)
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/multiprocessing/connection.py", line 308, in SocketClient
    s.connect(address)
  File "/usr/local/uvcdat/2016-02-17/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 2] No such file or directory

[durack1@oceanonly cmip5]$
```

**Comment by durack1** [comment]
@pochedls another candidate, should this be reincarnated in [cmiplib](https://github.com/durack1/cmiplib)? If yes, I'll copy it across

**Comment by pochedls** [comment]
I'm not exactly sure what the issue is here - it seems like this doesn't need to be migrated.

**Comment by durack1** [comment]
This was related to the ***dataset*** vs ***variable*** DRS/paths that Jeff was discussing, if we have smart code that ascertains pieces from a list this problem should no longer be an issue.. I agree, we can leave dead in this repo
